### ISSUE TITLE
How does model re-training impact the execution time of `dbt run`?

### ISSUE THREAD

**Issue by juszzz** [kristeligt-dagblad/dbt_ml#14]
I have a question (possibly BigQuery-specific) about best-practices for incorporating `dbt_ml` into a production workflow that consists of many DBT models (views and tables).  When creating a new BigQuery ML model using `dbt_ml`, it seems that `dbt run` will wait for the model to finish training and evaluation before it moves on to downstream DBT models (e.g., views that invoke `dbt_ml.predict`).  What happens though when the model has been trained and I invoke `dbt run` again?  It seems like `dbt run` again waits for the model to train before it moves on to running downstream models, rather than using the previously trained model and letting the re-training run in the background.

Is my understanding correct?  Will DBT always wait for a model to train and evaluate before it proceeds with running any downstream models?  If so, are there any best-practices for integrating ML models into an existing DBT pipeline in such a way that things like PR builds don't take a long time waiting for models to train?  I'm curious if others have grappled with this problem, and how they've solved it.

**Comment by rbjerrum** [comment]
Great question, @juszzz.

It is correct that when invoking `dbt run` with a selector that includes a BQ ML model as well as downstream models, the execution of the BQ ML model training is blocking. This is a consequence of the dependencies created by dbt through `ref()`'s. You could argue that re-training (not initial training) should be a background operation, however it would be tricky to have differentiating behaviour depending on whether or not the model exists already.

Instead, my team has resorted to using independent invocations of dbt for training and prediction. Say you have a `ml_model` named `my_regressor` with a downstream dependency called `my_predictions`. We then run model retraining on a weekly or monthly cadence using a selector like:
```sh
dbt run -m my_regressor
```
Predictions can then be run on another cadence, for example once an hour, using another selector:
```sh
dbt run -m my_regressor+ --exclude my_regressor
```
Or more explicit:
```sh
dbt run -m my_predictions
```

For the specific case of PR builds I would probably exclude ML models completely. Alternatively you could add some logic to limit the amount of training data when in CI in order to reduce time spent and cost:
```sql
{% if target.name == 'CI' %}
limit 1000
{% endif %
```

Finally you could experiment with [state](https://docs.getdbt.com/docs/guides/understanding-state) and [defer](https://docs.getdbt.com/reference/node-selection/defer) in order to only re-train models when they have changed (or doesn't exist yet).

**Comment by juszzz** [comment]
Wow, thanks for the comprehensive answer @rbjerrum!  That sounds pretty similar to the approach I was considering, namely, using tags like `ml_train` and `ml_predict` to differentiate train-time from predict-time models, and excluding training tags during most DBT runs.  I hadn't considered limiting training data based on the target, but that's an interesting idea.
